### ISSUE TITLE
when use network_cli get an error ""No authentication methods available"

### ISSUE THREAD

**Issue by yusufq8** [network-automation/napalm-vs-ansible#1]
when use network_cli getting an error 
"No authentication methods available"

**Comment by IPvSean** [comment]
Hey @yusufq8 , sorry for the delay, have been traveling :)

Have you checked out-> http://docs.ansible.com/ansible/latest/network/user_guide/network_debug_troubleshooting.html

It looks like this error specifically means->
>No password or SSH key supplied

Check out how I set the username and password for devices in the inventory itself-> 
https://github.com/network-automation/ansible-napalm-samples/blob/master/hosts

**Comment by yusufq8** [comment]
thanks IPvSean ok its working now
